name: eloquent
version: 3.0.0
description: eloquent query builder port from PHP Laravel
homepage: https://github.com/insinfo/eloquent_dart
#publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:  
  intl: '>=0.17.0 <3.0.0'
  #dargres: ^2.2.4
  dargres: ^3.0.2
 # dargres: 
   # path: ../dargres

  enough_convert: '>=1.6.0 <2.0.0' 
  
  #postgres:
    #path: ../postgresql-dart 
  # postgres v2
  postgres_fork: ^2.7.0
  #postgres:
    #git:
      #ref: master
      #url: https://github.com/insinfo/postgresql-dart-1.git

  mysql_client: ^0.0.27    
  # postgres v3 
  postgres: ^3.0.5
    

dev_dependencies:
  test: ^1.17.12 

  